### ISSUE TITLE
Indicate which "profile" is active

### ISSUE THREAD

**Issue by jkaberg** [martin31821/cpupower#69]
Just a very minor thing, but I thinks this great extension lacks an indicator telling me/the user which profile is currently active. 

Could be something as simple as an checkmark infront of the active profile in the dropdown menu?

**Comment by martin31821** [comment]
Already implemented. 
![screenshot from 2018-11-09 07-37-28](https://user-images.githubusercontent.com/5557633/48247111-63c13f80-e3f2-11e8-831e-80b9332d2e5c.png)

Make sure your profiles are defined correctly, specifically, check that the minimum percentate is correct, because pstate will overwrite it to a certain minimum value (see #25)

Example:
You have a profile defined with minimum 0%, maximum 100%, turbo enabled.
You enable this profile, pstate overwrites minimum to 19%.
As a result the values don't match the ones defined in the profile, so it isn't considered 'active'.
