### ISSUE TITLE
[enhancement] Icon color doesn't follow GNOME Shell theme color 

### ISSUE THREAD

**Issue by maxjf1** [martin31821/cpupower#79]
I'm using an custom GNOME shell theme (MacBuntu) that use dark icons and text on the shell.

The extension doesn't follow the theme color and uses an gray icon (other gnome extensions are using custom icons and the color is alright).

![image](https://user-images.githubusercontent.com/6114888/58282172-590d3d00-7d7b-11e9-8216-4b47fc8088ca.png)

![image](https://user-images.githubusercontent.com/6114888/58282310-c28d4b80-7d7b-11e9-87dd-de74d4e267f3.png)

**Comment by guekho64** [comment]
I'm not completely aware of the actual behaviour of this program, nor how it works internally, but, In my opinion, It'd be better to add one of these:

* An option to "Turn ON/OFF dark theme" (Only switching the icon from white to black should suffice...)
* Or implementing a way to let users add a custom icon to be displayed instead of the original one

Both would solve this specific issue, so I have no preference over one them.

If any of these options gets implemented, I can provide the dark icon if needed (It's not like it's that hard anyways...)

**Comment by maxjf1** [comment]
> I'm not completely aware of the actual behaviour of this program, nor how it works internally, but, In my opinion, It'd be better to add one of these:
> 
> * An option to "Turn ON/OFF dark theme" (Only switching the icon from white to black should suffice...)
> * Or implementing a way to let users add a custom icon to be displayed instead of the original one
> 
> Both would solve this specific issue, so I have no preference over one them.
> 
> If any of these options gets implemented, I can provide the dark icon if needed (It's not like it's that hard anyways...)

i think the problem isn't an dark and light icon

Gnome automatically set monochrome icon colors if they follow some pattern (wich i dont know)

For instance, i am now using an dark theme and it makes gnome icons completly white. this plugin uses an gray icon no matter the gnome settings. 

I don't know what is needed to make gnome automatically set the icon color, maybe using SVG or native icon...

![image](https://user-images.githubusercontent.com/6114888/60450962-5cf57000-9c01-11e9-8cd4-a2552793c564.png)
